### ISSUE TITLE
clarify requirements for honeybee-revit in a Readme 

### ISSUE THREAD

**Issue by ksobon** [ladybug-tools/honeybee-revit#10]
This is a new thread for the discussion that started in this issue: https://github.com/ladybug-tools/honeybee-revit/issues/6

I think we will need to clarify what the requirements are for the honeybee-revit plugin. Put together more detailed instructions.

**Comment by arif-hanif** [comment]
would be awesome to get an installer together that handles both requirements and revit add-in installation.

**Comment by ksobon** [comment]
I don't want to speak for @mostaphaRoudsari and @chriswmackey but I think last time we talked the idea was that we would offer instructions for free, and MSI installer would be for paying customers. I will let @mostaphaRoudsari make that call. In the meantime please follow the instructions that @chriswmackey put together for Rhino/Grasshopper.
