### ISSUE TITLE
add notifications for users to let them know that epw file path was not set

### ISSUE THREAD

**Issue by ksobon** [ladybug-tools/honeybee-revit#7]
Right now it proceeds to try and run the simulation which is causing a crash. We should let users know that it's a requirement. 

Related to this: https://github.com/ladybug-tools/honeybee-revit/issues/6

**Comment by ksobon** [comment]
@mostaphaRoudsari I actually simply made the "Run" button disabled if simulation path and epw file path were not set. You cannot run the simulation without them. That solves the issue of someone accidentally trying to run the simulation without the EPW file.

**Comment by mostaphaRoudsari** [comment]
Sounds good to me. I think most of the users are used to seeing deactivated buttons when the inputs are not provided.
